server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: spring-auth-server
            client-id: gateway
            client-secret: jdVWF2X2MO5X6jVrg9DeJ6diN2iKX9Vo
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://gateway:8000/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring-auth-server:
#            issuer-uri: ${GATEWAY_AUTHSERVER_ISSUER_URI:http://authserver:9000}
            issuer-uri: http://localhost:8001/realms/local
            user-name-attribute: preferred_username
#            issuer-uri: ${GATEWAY_AUTHSERVER_ISSUER_URI}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: http://frontend:[*],http://gateway:[*]
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: get_demo
          uri: ${GATEWAY_RESOURCE_URI:http://localhost:8080}
          predicates:
            - Method=GET
            - Path=/get
          filters:
            - TokenRelay=
            - SaveSession
        - id: post_demo
          uri: ${GATEWAY_RESOURCE_URI:http://localhost:8080}
          predicates:
            - Method=POST
            - Path=/post
          filters:
            - TokenRelay=
            - SaveSession
        - id: indirect_demo
          uri: ${GATEWAY_RESOURCE_URI:http://localhost:8080}
          predicates:
            - Method=GET
            - Path=/indirect
          filters:
            - TokenRelay=
            - SaveSession
        - id: auth_ping
          uri: ${GATEWAY_RESOURCE_URI:http://authserver:9000/auth}
          predicates:
            - Method=GET
            - Path=/api/v1/ping
          filters:
            - TokenRelay=
            - SaveSession
        - id: frontend
          uri: ${GATEWAY_FRONTEND_URI:http://frontend:4200}
          predicates:
            - Path=/**
          filters:
            - TokenRelay=
            - SaveSession
  data:
    redis:
      host: ${GATEWAY_REDIS_HOST:localhost}
      port: ${GATEWAY_REDIS_PORT:6379}
  session:
    store-type: redis


logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.gateway: INFO