server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: ${RESOURCE_AUTHSERVER_ISSUER_URI:http://authserver:9000}
          issuer-uri: http://localhost:8001/realms/local

props:
  jwksUri: http://localhost:8001/realms/local/protocol/openid-connect/certs